### ISSUE TITLE
The Webcam cant On 

### ISSUE THREAD

**Issue by cheahengsoon** [Microsoft/GazeInteractionApps#13]
Hi Team,

May I ask about any spec for webcam?
The webcam only for Surface?
Thank You.

**Comment by joncamp** [comment]
Short Answer: Not at this time

Long answer:
The GazeInteraction Apps uses the [GazeInteraction library](https://docs.microsoft.com/en-us/windows/communitytoolkit/gaze/gazeinteractionlibrary), which in turn relies on the [GazeInputSourcePreview API](https://docs.microsoft.com/en-us/uwp/api/windows.devices.input.preview.gazeinputsourcepreview) in Windows. The [GazeInputSourcePreview](https://docs.microsoft.com/en-us/uwp/api/windows.devices.input.preview.gazeinputsourcepreview) APIs hook into any webcam that supports the [Eye Tracker HID specification](http://www.usb.org/developers/hidpage/HUTRR74_-_Usage_Page_for_Head_and_Eye_Trackers.pdf).

Currently the only [trackers which support the specification](https://support.microsoft.com/en-us/help/4043921/windows-10-get-started-eye-control#supported-devices) are Tobii devices such as the Tobii Eye Tracker 4C or the EyeTech TM5 Mini.

There are a variety of webcam based eye tracking solutions online (commercial, open source, free, etc). If someone were to adapt them such that their data was plumbed to the OS as a HID device then they should work with the GazeInteraction library.
